apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: steven
  source:
    repoURL: https://github.com/swbsf/argo-dummy.git
    targetRevision: main
    path: ./helmfiles
    plugin:
      name: helmfile-v1.0
      env:
        - name: ENV_NAME
          value: dev
        - name: HELMFILE_FILE
          value: "helmfile.yaml"
  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
